// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;


namespace CSharp_Selenium
{

    public class BasePage
    {
        public static IWebDriver driver;

        public void Initialize()
        {
            ChromeOptions chromeOptions = new ChromeOptions();
            chromeOptions.AddArguments("--start-maximized");
            chromeOptions.AddArguments("disable-popup-blocking");
            chromeOptions.AddArguments("disable-infobars");
            chromeOptions.AddExcludedArgument("enable-automation");
            chromeOptions.AddArguments("--disable-extensions"); // to disable extension
            chromeOptions.AddArguments("--disable-notifications"); // to disable notification
            chromeOptions.AddArguments("--disable-application-cache");
            chromeOptions.AddAdditionalCapability("useAutomationExtension", false);
            driver = new ChromeDriver("C:\\Users\\x\\Desktop\\CSharp_Selenium\\CSharp_Selenium\\", chromeOptions);
            driver.Url = "https://www.trendyol.com/";
            driver.Manage().Window.Maximize();
        }

        public void TearDown()
        {
            driver.Quit();
        }

    }

}