// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.PageObjects;


namespace CSharp_Selenium
{

public class HomePage   : BasePage{

  public HomePage (IWebDriver driver) {
      HomePage.driver = driver;
      PageFactory.InitElements(driver,this);
  }

  [FindsBy(How = How.Id, Using = "support")]
  private IWebElement Support;

[FindsBy(How = How.Id, Using = "faqCategories-item-populer")]
  private IWebElement PopulerSorular;


public String GetPopulerSorular() { 
    Support.Click();
    WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(8));
    wait.Until(driver => PopulerSorular.Displayed);
    string assertText = PopulerSorular.GetAttribute("innerHTML");

    return assertText;
  }


}

}